spring.application.name=sender

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ravi.verma2320@gmail.com
spring.mail.password=gnheyxpxcmigjviw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true